gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#0048b3"
      - "bold"
    inactiveBorderColor:
      - "#d7cdb7"
    searchingActiveBorderColor:
      - "#095b62"
      - "bold"
    optionsTextColor:
      - "#0048b3"
    selectedLineBgColor:
      - "#e5dcc6"
    selectedRangeBgColor:
      - "#e5dcc6"
    cherryPickedCommitFgColor:
      - "#0048b3"
    cherryPickedCommitBgColor:
      - "#7a1f7a"
    unstagedChangesColor:
      - "#a12622"
    defaultFgColor:
      - "#28323a"
