-- vim.api.nvim_create_autocmd('LspAttach', {
--   group = vim.api.nvim_create_augroup('kickstart-lsp-attach', { clear = true }),
--   callback = function(event)
--     local ok, snacks = pcall(require, 'Snacks')
--     -- NOTE: Remember that Lua is a real programming language, and as such it is possible
--     -- to define small helper and utility functions so you don't have to repeat yourself.
--     --
--     -- In this case, we create a function that lets us more easily define mappings specific
--     -- for LSP related items. It sets the mode, buffer and description for us each time.
--     -- local map = function(keys, func, desc, mode)
--     --   mode = mode or 'n'
--     --   vim.keymap.set(mode, keys, func, { buffer = event.buf, desc = 'LSP: ' .. desc })
--     -- end

--     -- LSP keymaps are now configured in lua/kickstart/config/keymaps.lua
--   end,
-- })
